import assert from 'node:assert/strict';
import {resolveDrawingAnchor} from '../src/drawing/annotations';
import type {DrawingProjectionDto, DrawingTopologyAnchorRefDto, DrawingViewDto} from '../src/engine/types';
const view = {position:[0,0],scale:2} as DrawingViewDto;
const ref: DrawingTopologyAnchorRefDto = {body_id:1,edge_id:7,edge_key:'original',endpoint:'end',fallback_point:[0,0,6],circle_center:false};
const anchor = {body_id:1,edge_id:7,edge_key:'original',endpoint:'end' as const,model_point:[0,0,8] as [number,number,number],point:[0,8] as [number,number],hidden:false};
const projection = {anchors:[anchor],circles:[],bounds:[0,0,40,8]} as unknown as DrawingProjectionDto;
assert.equal(resolveDrawingAnchor(ref,view,projection)?.anchor.model_point[2],8,'Use current geometry after edit, not stored fallback');
assert.equal(resolveDrawingAnchor(ref,view,{...projection,anchors:[{...anchor,edge_key:'replacement'}]}),null,'A reused numeric ID must not retarget a dimension');
assert.equal(resolveDrawingAnchor(ref,view,{...projection,anchors:[{...anchor,edge_id:9}]})?.resolution,'edge_key','Stable key can recover a renumbered edge');
const circle = {body_id:1,edge_id:7,edge_key:'replacement',center_model:[0,0,8],center:[0,8],hidden:false};
assert.equal(resolveDrawingAnchor({...ref,circle_center:true},view,{...projection,circles:[circle]} as unknown as DrawingProjectionDto),null,'Circle-center dimensions must also reject ID reuse');
console.log('PASS drawing dimension geometry propagation, stable keys and topology replacement');
