//! The same ZIP container contract as src/files/nbcad.ts. The native engine,
//! not this container writer, owns model validation and geometry recomputation.
use anyhow::{ensure, Context, Result};
use serde_json::{json, Value};
use std::io::{Cursor, Read, Write};

pub(crate) fn encode(model_json: &str, application_version: &str) -> Result<Vec<u8>> {
    let model: Value = serde_json::from_str(model_json).context("Parse exported project model")?;
    ensure!(
        model["format"] == "nbcad-project"
            && model["schema_version"].as_u64().is_some_and(|v| v > 0),
        "The engine produced an invalid project model"
    );
    ensure!(
        !application_version.trim().is_empty(),
        "Missing engine version"
    );
    let manifest = json!({
        "format": "nbcad-project",
        "container_version": 1,
        "model": "model.json",
        "model_schema_version": model["schema_version"],
        "application": "noBS CAD",
        "application_version": application_version,
        // Generated artifacts use an epoch, not a misleading wall-clock save
        // date. Together with fixed ZIP timestamps this makes exports repeatable.
        "saved_at": "1970-01-01T00:00:00Z"
    });
    let mut archive = zip::ZipWriter::new(Cursor::new(Vec::new()));
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .last_modified_time(zip::DateTime::default());
    archive.start_file("manifest.json", options)?;
    archive.write_all(&serde_json::to_vec_pretty(&manifest)?)?;
    archive.start_file("model.json", options)?;
    // Native model text can contain hash-map iteration order (for example,
    // sketch dimension placements). Value's sorted maps normalize that order
    // without dropping fields; float_roundtrip preserves the original numbers.
    archive.write_all(&serde_json::to_vec_pretty(&model)?)?;
    Ok(archive.finish()?.into_inner())
}

/// Read back the actual generated bytes, not a second copy of the source model.
pub(crate) fn model(bytes: &[u8]) -> Result<String> {
    let mut archive = zip::ZipArchive::new(Cursor::new(bytes))?;
    let manifest: Value = serde_json::from_reader(archive.by_name("manifest.json")?)?;
    ensure!(
        archive.len() == 2
            && manifest["format"] == "nbcad-project"
            && manifest["container_version"] == 1
            && manifest["model"] == "model.json",
        "Invalid generated project container"
    );
    let mut model_json = String::new();
    archive
        .by_name("model.json")?
        .read_to_string(&mut model_json)?;
    let model: Value = serde_json::from_str(&model_json)?;
    ensure!(
        model["format"] == "nbcad-project"
            && model["schema_version"].as_u64().is_some_and(|v| v > 0)
            && manifest["model_schema_version"] == model["schema_version"],
        "Generated project manifest/model mismatch"
    );
    Ok(model_json)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn headless_archive_preserves_all_model_fields_and_is_reproducible() {
        let model_json = json!({"format":"nbcad-project","schema_version":7,
            "document":{"name":"Bench Ω","history":{"features":[{"id":1}]}},
            "sketches":[{"name":"Editable sketch"}], "assembly":{"joints":[1]},
            "drawings":{"sheets":[1]}, "cam":{"setups":[1]},
            "visibility":{"hidden_body_ids":[2]}, "body_appearances":[{"body_id":1}]
        })
        .to_string();
        let bytes = encode(&model_json, "0.2.0").unwrap();
        assert_eq!(bytes, encode(&model_json, "0.2.0").unwrap());
        assert_eq!(
            serde_json::from_str::<Value>(&model(&bytes).unwrap()).unwrap(),
            serde_json::from_str::<Value>(&model_json).unwrap()
        );
        let mut archive = zip::ZipArchive::new(Cursor::new(bytes)).unwrap();
        let manifest: Value =
            serde_json::from_reader(archive.by_name("manifest.json").unwrap()).unwrap();
        assert_eq!(manifest["application_version"], "0.2.0");
        assert_eq!(manifest["model_schema_version"], 7);
        assert_eq!(manifest["saved_at"], "1970-01-01T00:00:00Z");
    }

    #[test]
    fn equivalent_model_text_produces_identical_archives() {
        let a = r#"{"format":"nbcad-project","schema_version":7,"placements":{"5":{"x":32.5,"y":-10.0},"6":{"x":-10.0,"y":32.5}}}"#;
        let b = r#"{ "placements": {"6":{"y":32.5,"x":-10.0},"5":{"y":-10.0,"x":32.5}}, "schema_version":7, "format":"nbcad-project" }"#;
        assert_eq!(encode(a, "0.2.0").unwrap(), encode(b, "0.2.0").unwrap());
    }

    #[test]
    fn malformed_models_and_archives_are_rejected() {
        for text in [
            "not JSON",
            "{}",
            r#"{"format":"nbcad-project","schema_version":0}"#,
            r#"{"format":"nbcad-project","schema_version":1.5}"#,
        ] {
            assert!(encode(text, "0.2.0").is_err());
        }
        assert!(model(b"not a ZIP").is_err());
        assert!(encode(r#"{"format":"nbcad-project","schema_version":7}"#, "").is_err());
    }
}
